// <auto-generated />
namespace SchoolWebAuth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class teachrforeignkey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(teachrforeignkey));
        
        string IMigrationMetadata.Id
        {
            get { return "202106160902558_teachr foreign key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
